config/routes.rb
Rails.application.routes.draw do
  get 'sitemap', to: redirect('https://okworks-production.s3-ap-northeast-1.amazonaws.com/sitemaps/sitemap.xml.gz')
  post 'subscriptions/create'
  root 'home#index'
  resources :jobs
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  JOB_LIMIT = 10
  before_action :set_select_box, :set_skill_amont_charts, :set_skill_amont_charts_sp, :set_median_rewards_by_skills, :set_median_rewards_by_skills_sp
  before_action :set_high_reward_ranking, only: :index

  def index
    @all_job_count = Job.enabled.count.to_s(:delimited)
    @q = Job.enabled.order(created_at: 'DESC').limit(JOB_LIMIT).ransack(params[:q])
    @jobs = @q.result(distinct: true)
    @logos = ['prosheet_logo.png', 'pebank.png', 'levtech.png', 'midworks.png', 'itpropartners.png'].take(12)
  end

private   

  def set_high_reward_ranking
    @high_reward_jobs = Job.enabled.order(max_reward: 'DESC').limit(10)
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def set_skill_amont_charts
    skill_amount = cache_skill_amount
    name = skill_amount.keys
    data = skill_amount.values
    @skill_amount_bar = LazyHighCharts::HighChart.new("graph") do |f|
      f.chart(:type => "column")
      f.title(:text => "技術別の案件数")
      f.xAxis(:categories => name)
      f.series(:data => data)
      f.legend(enabled: false)
    end
  end

  def set_skill_amont_charts_sp
    skill_amount = cache_skill_amount_sp
    name = skill_amount.keys
    data = skill_amount.values
    @skill_amount_bar_sp = LazyHighCharts::HighChart.new("graph") do |f|
      f.chart(:type => "column")
      f.title(:text => "技術別の案件数")
      f.xAxis(:categories => name)
      f.series(data: data)
      f.legend(enabled: false)
    end
  end

  def set_median_rewards_by_skills
    skill_amount = cache_median_rewards
    name = skill_amount.keys
    data = skill_amount.values
    @skill_average_rewards_bar = LazyHighCharts::HighChart.new("graph") do |f|
      f.chart(:type => "column")
      f.title(:text => "技術別の単価/日の中央値")
      f.yAxis(
          title: {text: ''},
          labels: {
            formatter: "function(){
                return Highcharts.numberFormat(this.value, 0, '.', ',') +'円'
            }".js_code,
          }
      )
      f.xAxis(:categories => name)
      f.series(:data => data)
      f.legend(enabled: false)
    end
  end

  def set_median_rewards_by_skills_sp
    skill_amount = cache_median_rewards_sp
    name = skill_amount.keys
    data = skill_amount.values
    @skill_average_rewards_bar_sp = LazyHighCharts::HighChart.new("graph") do |f|
      f.chart(:type => "column")
      f.title(:text => "技術別の単価/日の中央値")
      f.yAxis(
          title: {text: ''},
          labels: {
            formatter: "function(){
                return Highcharts.numberFormat(this.value, 0, '.', ',') +'円'
            }".js_code,
          }
      )
      f.xAxis(:categories => name)
      f.series(:data => data)
      f.legend(enabled: false)
    end
  end

  def cache_skill_amount
    Rails.cache.fetch('cache_skill_amount', expires_in: 1.hour) do
      skill_amount_hash = {}
      skills = Skill.all
      skills.each do |skill|
        amount = JobSkill.where(skill_id: skill.id).size
        skill_amount_hash[skill.name] = amount
      end
      skill_amount_hash
    end
  end

  def cache_skill_amount_sp
    Rails.cache.fetch('cache_skill_amount_sp', expires_in: 1.hour) do
      skill_amount_hash = {}
      skills = Skill.all
      skills.each do |skill|
        amount = JobSkill.where(skill_id: skill.id).size
        skill_amount_hash[skill.name] = amount
        if skill_amount_hash.size > 10
          min_value = skill_amount_hash.values.min
          min_key = skill_amount_hash.key(min_value)
          skill_amount_hash.delete min_key
        end
      end
      skill_amount_hash
    end
  end

  def cache_median_rewards
    Rails.cache.fetch('cache_median_rewards', expires_in: 1.hour) do
      median_rewards_hash = {}
      skills = Skill.all
      skills.each do |skill|
        job_ids = JobSkill.where(skill_id: skill.id).pluck :job_id
        jobs_rewards = Job.where(id: job_ids).pluck :average_reward
        median_rewards = calc_median_reward(jobs_rewards)
        # クローリング先のサイトにおいて入力ミスがあった時、
        # 平均値だと大きくぶれてしまうので、中央値を使用
        median_rewards_hash[skill.name] = median_rewards.to_i
      end
      median_rewards_hash
    end
  end

  def cache_median_rewards_sp
    Rails.cache.fetch('cache_median_rewards_sp', expires_in: 1.hour) do
      median_rewards_hash = {}
      skills = Skill.all
      skills.each do |skill|
        job_ids = JobSkill.where(skill_id: skill.id).pluck :job_id
        jobs_rewards = Job.where(id: job_ids).pluck :average_reward
        median_rewards = calc_median_reward(jobs_rewards)
        # クローリング先のサイトにおいて入力ミスがあった時、
        # 平均値だと大きくぶれてしまうので、中央値を使用
        median_rewards_hash[skill.name] = median_rewards.to_i
        if median_rewards_hash.size > 10
          min_value = median_rewards_hash.values.min
          min_key = median_rewards_hash.key(min_value)
          median_rewards_hash.delete min_key
        end
      end
      median_rewards_hash
    end
  end

  def calc_median_reward(jobs_rewards)
    if jobs_rewards.size == 0
      median_rewards = 0
    else
      median_rewards = (jobs_rewards.size % 2).zero? ? jobs_rewards[jobs_rewards.size/2 - 1, 2].inject(:+) / 2.0 : jobs_rewards[jobs_rewards.size/2]
    end
    return median_rewards
  end










end

app/views/home/_charts.html.haml
%h4 統計データ
.pc_chart
  = high_chart("skill_amount_bar", skill_amount_bar) 
.sp_chart
  = high_chart("skill_amount_bar_sp", skill_amount_bar_sp) 
.pc_chart
  = high_chart("skill_average_rewards_bar", skill_average_rewards_bar) 
.sp_chart
  = high_chart("skill_average_rewards_bar_sp", skill_average_rewards_bar_sp) 

app/views/home/_high_reward_list_job.html.haml
%a.list-group-item.list-group-item-action.flex-column.align-items-start{:href => "#{job_url(job.id)}"}
  .d-flex.w-100
    %div
      %h5.mb-1= job.title
      %div
        = raw reward_html_helper(job)
  - job.skills.each do |skill|
    %span.badge.badge-primary= skill.name

app/views/home/_high_reward_ranking.html.haml
.container
  %h4 高単価案件/求人ランキング
  .list-group.home-list-group{:style => "margin-top:20px;"}
    - jobs.each do |job|
      = render 'high_reward_list_job', job: job

app/views/home/_latest_jobs.html.haml
.container
  %h4 最新案件
  .list-group.home-list-group{:style => "margin-top:20px;"}
    - jobs.each do |job|
      %a.list-group-item.list-group-item-action.flex-column.align-items-start{:href => "#{job_url(job.id)}"}
        .d-flex.w-100.justify-content-between
          %h5.mb-1= job.title
          %small= job.created_at.strftime("%Y/%m/%d")
        - job.skills.each do |skill|
          %span.badge.badge-primary= skill.name

app/views/home/_search_form.html.haml
.pc-search{class: "#{'alert alert-dark' if pc_background}"}
  = search_form_for(@q, url: jobs_path) do |f|
    %div.form-row
      .input-group.col-md-12.mb-3
        = f.search_field :title_or_detail_cont, class: "form-control"
        .input-group-append
          %button.btn.btn-dark{:type => "submit"} 検索
    %div.form-row.top-select-boxes
      %div.form-group.col-md-3
        = label_tag '', '技術', class: 'top-label'
        = f.collection_select :skills_id_eq, @skills, :id, :name, {include_blank: '指定なし'}, {class: "form-control"}
      %div.form-group.col-md-3
        = label_tag '', '職種', class: 'top-label'
        = f.collection_select :job_type_id_eq, @job_types, :id, :name, {include_blank: '指定なし'}, {class: "form-control"}
      %div.form-group.col-md-3
        = label_tag '', '稼働日数', class: 'top-label'
        = select_tag :desired_number_of_days, options_for_select(@work_days, selected: params[:desired_number_of_days]), include_blank: '指定なし', class: "form-control"
      %div.form-group.col-md-3
        = label_tag '', '日給', class: 'top-label'
        = f.select :average_reward_gteq, @average_rewards, {include_blank: '指定なし'}, {class: "form-control"}

- if request.path == '/'
  .toppage-margin

.sp-search
  / Button trigger modal
  %button.btn.btn-dark.search-button.mb-3{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
    検索する
  / Modal
  #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        = search_form_for(@q, url: jobs_path) do |f|
          .modal-body
            %div.form-row
              %div.form-group.col-md-3
                = label_tag '', 'キーワード', class: 'top-label'
                = f.search_field :title_or_detail_cont, class: "form-control"
              %div.form-group.col-md-3
                = label_tag '', '技術', class: 'top-label'
                = f.collection_select :skills_id_eq, @skills, :id, :name, {include_blank: '指定なし'}, {class: "form-control"}
              %div.form-group.col-md-3
                = label_tag '', '職種', class: 'top-label'
                = f.collection_select :job_type_id_eq, @job_types, :id, :name, {include_blank: '指定なし'}, {class: "form-control"}
              %div.form-group.col-md-3
                = label_tag '', '稼働日数', class: 'top-label'
                = select_tag :desired_number_of_days, options_for_select(@work_days, selected: params[:desired_number_of_days]), include_blank: '指定なし', class: "form-control"
              %div.form-group.col-md-3
                = label_tag '', '日給', class: 'top-label'
                = f.select :average_reward_gteq, @average_rewards, {include_blank: '指定なし'}, {class: "form-control"}
          .modal-footer
            %button.btn.btn-dark{:type => "submit"} 検索

app/views/home/index.html.haml
%nav.nav-bar-top.top-area
  .container.top-detail-area
    %h1.h2.top_copy 日本最大のIT系フリーランス案件/求人検索サービス
    %h4.top_copy_sub
      = "#{@all_job_count}件の案件/求人を掲載中"
    .form-wrapper
      = render partial: 'home/search_form', locals: {pc_background: false}
.container
  .text-center
    %h4.mb-4 OKWorksとは
  .row.text-center
    .col-md-12
      %p
        OKWorksは、IT系のフリーランスエンジニア・デザイナーなどを対象に、企業とフリーランスのマッチングを支援します。
      %p 
        %small
          フレキシブルな働き方や高収入を実現できる、IT系のフリーランスという働き方が拡大しています。
          しかし、継続的に仕事を獲得するための営業活動は、時間や労力がかかります。
          一方、社会的に、エンジニア、デザイナーなどIT系人材の需要が急増し、人手不足が発生しています。
  .text-center
    %h4.mb-4 フリーランスを応援する3つのOK
    .row
      .col-md-4.mb-7.mb-md-0
        .text-center.px-lg-3
          %img.max-width-14.mb-3{:src => "/assets/time.svg", :width => "30%"}/
          %h3.h4 フレキシブルな働き方OK
          %p.mb-2 週3日だけ、4日だけなどの生活スタイルや希望に合わせた働き方はもちろん、副業可能な案件がたくさんあります。
      .col-md-4.mb-7.mb-md-0
        .text-center.px-lg-3
          %img.max-width-14.mb-3{:src => "/assets/rocket.svg", :width => "30%"}/
          %h3.h4 リモートOK
          %p.mb-2 常駐型だけではなく、フルリモート案件や一部リモート可など、多くの案件で、リモートでの働き方が認められています。
      .col-md-4
        .text-center.px-lg-3
          %img.max-width-14.mb-3{:src => "/assets/money.svg", :width => "30%"}/
          %h3.h4 高収入＆面白い仕事OK
          %p.mb-2 専門性を活かしたハイスキルな求人ばかりなので、高収入かつユニークで面白い先進的な仕事をを見つけることができます。
  .text-center
    %h4.mb-4 豊富な案件から探せる
  .row.text-center
    .col-md-12
      %p
        OKWorksは、WEB上のフリーランス案件を収集しているため、非常に多くの案件の中から探すことが可能です。
      .row
        - @logos.each do |logo|
          .col-3.col-sm-2.mb-2= image_tag "/assets/service_logos/#{logo}", width: '100%'

= render 'latest_jobs', jobs: @jobs
= render 'high_reward_ranking', jobs: @high_reward_jobs
.container
  = render partial: 'charts', locals: {skill_amount_bar: @skill_amount_bar, skill_amount_bar_sp: @skill_amount_bar_sp, skill_average_rewards_bar: @skill_average_rewards_bar, skill_average_rewards_bar_sp: @skill_average_rewards_bar_sp}