config/routes.rb
Rails.application.routes.draw do
  get 'sitemap', to: redirect('https://okworks-production.s3-ap-northeast-1.amazonaws.com/sitemaps/sitemap.xml.gz')
  post 'subscriptions/create'
  root 'home#index'
  resources :jobs
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  serialize :conditions

  def self.new_subscription(email, skill_id = nil, job_type_id = nil)
    Subscription.create(email: email, conditions: {skill_id: skill_id, job_type_id: job_type_id})
  end

  def send_mail
    begin
      SubscriptionsMailer.jobs(self).deliver_now
    rescue => exception      
    end
  end

  def self.send_mails
    subscriptions = self.all
    subscriptions.each{|subscription| subscription.send_mail}
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    subscription = Subscription.new_subscription(params[:email], params['subscription_skill_id'], params['subscription_job_type_id'])
    cookies.permanent[:suscribed] = 'true'
    cookies.permanent[:subscription_id] = subscription.id
    redirect_to params[:last_url], notice: '案件情報の購読を開始しました。'
  end  
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.haml
- if cookies.permanent[:suscribed] != 'true'
  .container.mt-3.mb-3
    = form_with url: subscriptions_create_path, method: :post do |f|
      %input{:name => "skill_id", :type => "hidden", :value => params[:skill_ids]}/
      %input{:name => "last_url", :type => "hidden", :value => request.original_url}/
      .card
        .card-body{:align => "center"}
          最新の案件情報をメールで受取りませんか？
          %br
          %small OKWorksが最新の案件情報を定期的にお届けします。
          .col-md-6.col-12.mt-2
            %input#email.form-control{:name => "email", :placeholder => "メールアドレス", :required => "", :type => "email"}/
          %div.form-row.top-select-boxes.mt-3
            %div.form-group.col-md-3
            %div.form-group.col-md-3
              = f.collection_select :subscription_skill_id, @skills, :id, :name, {include_blank: 'スキル（指定なし）', selected: @subscription_skill}, {class: "form-control"}
            %div.form-group.col-md-3
              = f.collection_select :subscription_job_type_id, @job_types, :id, :name, {include_blank: '職種（指定なし）', selected: @subscription_job_type}, {class: "form-control"}
            %div.form-group.col-md-3
          %button.btn.btn-primary.mt-2{:type => "submit"} 登録する